---
version: "2.0"

services:
  postgres:
    image: postgres:12 
    expose:
      - port: 5432
        to:
          - service: web
    env:
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<database>

  web:
    image: <username>/<image-name>:<tag>
    depends-on: postgres
    expose:
      - port: 80
        as: 80
        accept: 
          - <domain>
        to:
          - global: true
    env:
      - PYTHONPATH=.
      - DATABASE_URL=postgresql://<user>:<password>@postgres:5432/<database>

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    postgres:
      resources:
        cpu:
          units: 1 
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 1000
        postgres: 
          denom: uakt
          amount: 3000

deployment:
  postgres:
    dcloud:
      profile: postgres
      count: 1
  web:
    dcloud:
      profile: web
      count: 1
  